###
POST http://localhost:8080/api/v1/links/shorten
Content-Type: application/json

{
  "body": {
    "link": "https://google.com",
    "endTime": "2024-10-06T12:00:00",
    "description": "google.com",
    "isActive": true
  }
}
###
DELETE http://localhost:8080/api/v1/links?id=92ae4fa5-89e8-44b5-84fe-91a10d2c141f

###
PUT http://localhost:8080/api/v1/links
Content-Type: application/json

{
  "body": {
    "id": "",
    "link": "https://google.com",
    "endTime": "2024-10-06T12:00:00",
    "description": "google.com",
    "isActive": true
  }
}

###
GET http://localhost:8080/api/v1/go?ref=2nksYYDuqj