###
POST http://localhost:8080/api/v1/link-infos
Content-Type: application/json

{
  "body": {
    "link": "https://google.com",
    "endTime": "2024-10-06T12:00:00",
    "description": "google.com",
    "isActive": true
  }
}
###
DELETE http://localhost:8080/api/v1/link-infos/{{id}}

###
PUT http://localhost:8080/api/v1/link-infos
Content-Type: application/json

{
  "body": {
    "id": "",
    "link": "https://google.com",
    "endTime": "2024-10-06T12:00:00",
    "description": "google.com",
    "isActive": true
  }
}

###
GET http://localhost:8080/api/v1/short-link/qwe

###
POST http://localhost:8080/api/v1/link-infos/filter
Content-Type: application/json

{
  "body": {
    "linkPart": null,
    "descriptionPart": "go",
    "fromEndTime": "2024-10-06T12:00:00",
    "toEndTime": "2026-10-06T12:00:00",
    "isActive": true
  }
}