version: '3.8'
name: 'link-shortener'

services:
  link-shortener-postgresql:
    image: postgres:17-alpine3.21
    container_name: link-shortener-postgresql
    ports:
      - "${POSTGRES_PORT:-5454}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-test}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-pswd}"
      POSTGRES_DB: "${POSTGRES_DB:-link_shortener}"
    volumes:
      - ./appdata/link_shortener_postgresql:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

volumes:
  postgres_data:
    driver: local